use crate::types::{CheckStatus, ScanResult};

#[tauri::command]
pub fn generate_report(results: ScanResult) -> Result<String, String> {
    let mut md = String::new();
    md.push_str("# OneNote Migration Readiness Report\n\n");
    md.push_str(&format!("**Generated:** {}\n\n", results.timestamp));
    md.push_str(&format!("**System:** {}\n\n", results.os_info));

    let overall_label = match results.overall {
        CheckStatus::Pass => "PASS - All checks passed",
        CheckStatus::Warning => "WARNING - Some checks need attention",
        CheckStatus::Fail => "FAIL - Issues detected",
        CheckStatus::Skipped => "SKIPPED - No applicable checks",
    };
    md.push_str(&format!("**Overall:** {}\n\n", overall_label));
    md.push_str("---\n\n");
    md.push_str("## Results\n\n");
    md.push_str("| Check | Status | Detail |\n");
    md.push_str("|-------|--------|--------|\n");

    for check in &results.checks {
        let status_str = match check.status {
            CheckStatus::Pass => "PASS",
            CheckStatus::Warning => "WARNING",
            CheckStatus::Fail => "FAIL",
            CheckStatus::Skipped => "SKIPPED",
        };
        md.push_str(&format!(
            "| {} | {} | {} |\n",
            check.label, status_str, check.message
        ));
    }

    // Remediation section if there are failures
    let failed: Vec<_> = results
        .checks
        .iter()
        .filter(|c| c.status != CheckStatus::Pass && c.status != CheckStatus::Skipped && c.remediation.is_some())
        .collect();

    if !failed.is_empty() {
        md.push_str("\n---\n\n## Remediation Steps\n\n");
        for (i, check) in failed.iter().enumerate() {
            md.push_str(&format!(
                "{}. **{}**: {}\n\n",
                i + 1,
                check.label,
                check.remediation.as_ref().unwrap()
            ));
        }
    }

    md.push_str("\n---\n\n");
    md.push_str("*Generated by OneNote Migration Readiness Tool*\n");

    Ok(md)
}

#[tauri::command]
pub fn save_report(markdown: String, path: String) -> Result<(), String> {
    std::fs::write(&path, &markdown).map_err(|e| format!("Failed to write report: {}", e))
}
